name: Get IPCC

on:
   workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest  # 运行环境

    steps:
    - name: Download ipsw
      run: |
        wget https://updates.cdn-apple.com/2025SpringSeed/fullrestores/072-95155/E567A28F-9337-4228-8CD5-962AA3C32EC3/iPhone14,2_18.5_22F5042g_Restore.ipsw
        ls
        
    - name: Unzip 
      run: |
        sudo apt update
        sudo apt install unzip
        mv iPhone14,2_18.5_22F5042g_Restore.ipsw iPhone.zip
        unzip iPhone.zip
        ls













        
