name: Get IPCC

on:
   push:
   workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest  # 运行环境

    steps:
    - name: Install Software
      run: |
        sudo apt update
        sudo apt install aria2
        sudo apt install unzip
        sudo apt install snapd
        sudo snap install ipsw
        
    - name: Download ipsw
      run: |
        echo "下载固件......"
        url="https://updates.cdn-apple.com/2025SpringSeed/fullrestores/072-95155/E567A28F-9337-4228-8CD5-962AA3C32EC3/iPhone14,2_18.5_22F5042g_Restore.ipsw"
        aria2c --summary-interval=1 --console-log-level=notice --show-console-readout=true -o iPhone.ipsw $url
        ls
        filename=$(basename "$url")  # 获取文件名部分
        version=$(echo "$filename" | awk -F'_' '{print $3}')  # 提取22F5042g
        device=$(echo "$filename" | awk -F'_' '{print $1}')  # 提取iPhone14,2
        echo "${version}__${device}"  # 输出22F5042g__iPhone14,2
        echo "FOLDER_NAME=${version}__${device}" >> $GITHUB_ENV
        
    - name: Get AEA and AEA PEMs
      run: |
        echo "获取aea.pem......"
        ipsw extract --fcs-key iPhone.ipsw
        echo "获取aea......"
        ipsw extract --dmg sys iPhone.ipsw
        
    - name: Ipsw aea
      run: |
        ls
        echo "到达目录${{ env.FOLDER_NAME}}"
        cd "${{ env.FOLDER_NAME}}"
        ls
        max_file=$(find . -type f -name "*.dmg.aea" -exec du -b {} + | sort -rn | head -n 1 | awk '{print $2}')
        echo "找到文件：$max_file"
        stripped_name=$(basename "$max_file" .dmg.aea)
        echo "去后缀文件名为：$stripped_name"
        echo "解密中......"
        ipsw fw aea $max_file
        ls
        mv *.dmg out.zip
        unzip out.zip
        echo "CLEAN_NAME=$stripped_name" >> $GITHUB_ENV

    - name: Get ipcc
      run: |
        echo "获取ipcc......"
        cd "${{ env.CLEAN_NAME}}"
        ls
        cd System
        ls
        cd Library
        ls
        cd Carrier Bundles
        ls
        cd iPhone
        ls











        
